# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a75c56540d492b9e5e49e7e77697f85e"
application_url = "https://cost-certified-sticker-farmer.trycloudflare.com"
embedded = true
name = "demo-app-sohana"
handle = "demo-app-sohana"

[build]
include_config_on_deploy = true
dev_store_url = "one-theme-2025.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cost-certified-sticker-farmer.trycloudflare.com/auth/callback",
  "https://cost-certified-sticker-farmer.trycloudflare.com/auth/shopify/callback",
  "https://cost-certified-sticker-farmer.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
